Added Single Instance limitation to the program
com.egg.grabber.Tests : added a single instance test using websocket

com.egg.grabber.customException: added an ExceptionUI frame which will server as a dialog box for all the exceptions that occur

Removed the static modifiers of the member UI components in GrabberGUI class

Modified paths to use System.getProperty("user.home") instead of hard-coding to make it cross-platform compatible

Enforced single instance of the application using Web Socket (make sure that the port 42069 is open and not used by any application). This will open a dialogue box from ExceptionUI if an instance is already running.